# Generated by Django 6.0.6 on 2026-07-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='purchase',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tipo_pago',
            field=models.CharField(choices=[('CONTADO', 'CONTADO'), ('CREDITO', 'CREDITO')], default='CONTADO', max_length=10),
        ),
    ]
