# Generated by Django 6.0.6 on 2026-07-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_alter_purchase_numero_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasedetail',
            options={'ordering': ['id'], 'verbose_name': 'Purchase Detail', 'verbose_name_plural': 'Purchase Details'},
        ),
    ]
