# Generated by Django 6.0.6 on 2026-07-13 10:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchasing', '0005_alter_purchasedetail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA')], default='PENDIENTE', max_length=15)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='purchasing.purchase')),
            ],
            options={
                'verbose_name': 'Cuota de Compra',
                'verbose_name_plural': 'Cuotas de Compra',
                'ordering': ['compra', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuotaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El pago debe ser mayor a cero.')])),
                ('observacion', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='creditos_compras.cuotacompra')),
            ],
            options={
                'verbose_name': 'Pago de Cuota de Compra',
                'verbose_name_plural': 'Pagos de Cuotas de Compra',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuotacompra',
            constraint=models.UniqueConstraint(fields=('compra', 'numero'), name='uq_cuotacompra_compra_numero'),
        ),
        migrations.AddConstraint(
            model_name='cuotacompra',
            constraint=models.CheckConstraint(condition=models.Q(('saldo__gte', 0), ('saldo__lte', models.F('valor'))), name='ck_cuotacompra_saldo_rango'),
        ),
    ]
