# Generated by Django 6.0.6 on 2026-07-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_compras', '0002_pagocuotacompra_descuento_pronto_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuotacompra',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('PAYPAL', 'PayPal')], default='EFECTIVO', max_length=15),
        ),
        migrations.AddField(
            model_name='pagocuotacompra',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
