# Generated by Django 6.0.6 on 2026-07-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0008_alter_invoice_numero_not_null'),
        ('purchasing', '0005_alter_purchasedetail_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Liquidación de compra')], max_length=2)),
                ('ruc_emisor', models.CharField(max_length=13)),
                ('tipo_ambiente', models.CharField(default='1', max_length=1)),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('secuencial', models.CharField(max_length=9)),
                ('codigo_numerico', models.CharField(max_length=8)),
                ('tipo_emision', models.CharField(default='1', max_length=1)),
                ('digito_verificador', models.CharField(max_length=1)),
                ('clave_acceso', models.CharField(max_length=49, unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADO', 'Firmado'), ('ENVIADO', 'Enviado'), ('EN_PROCESAMIENTO', 'En procesamiento'), ('AUTORIZADO', 'Autorizado'), ('RECHAZADO', 'Rechazado'), ('DEVUELTO', 'Devuelto')], default='BORRADOR', max_length=20)),
                ('xml_firmado', models.TextField(blank=True)),
                ('firma_hash', models.CharField(blank=True, max_length=64)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_firmado', models.DateTimeField(blank=True, null=True)),
                ('fecha_enviado', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta_sri', models.DateTimeField(blank=True, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='purchasing.purchase')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Comprobante Electrónico',
                'verbose_name_plural': 'Comprobantes Electrónicos',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('compra__isnull', True), ('factura__isnull', False)), models.Q(('compra__isnull', False), ('factura__isnull', True)), _connector='OR'), name='comprobante_exactamente_una_referencia')],
            },
        ),
    ]
