# Generated by Django 6.0.6 on 2026-06-25 07:59

import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_brand_description_alter_brand_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[shared.validators.validate_only_letters], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[shared.validators.validate_only_letters], verbose_name='Apellido'),
        ),
    ]
