# Generated by Django 6.0.6 on 2026-07-13 09:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0008_alter_invoice_numero_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADA', 'PAGADA')], default='PENDIENTE', max_length=15)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Cuota de Venta',
                'verbose_name_plural': 'Cuotas de Venta',
                'ordering': ['factura', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El pago debe ser mayor a cero.')])),
                ('observacion', models.TextField(blank=True)),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='creditos_ventas.cuotaventa')),
            ],
            options={
                'verbose_name': 'Pago de Cuota',
                'verbose_name_plural': 'Pagos de Cuotas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cuotaventa',
            constraint=models.UniqueConstraint(fields=('factura', 'numero'), name='unique_cuota_numero_por_factura'),
        ),
        migrations.AddConstraint(
            model_name='cuotaventa',
            constraint=models.CheckConstraint(condition=models.Q(('saldo__gte', 0), ('saldo__lte', models.F('valor'))), name='cuotaventa_saldo_valido'),
        ),
    ]
