# Generated by Django 6.0.6 on 2026-07-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos_ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocuotaventa',
            name='descuento_pronto_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagocuotaventa',
            name='interes_mora',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
